[project]
name = "break-timer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.2.1",
    "psutil>=7.0.0",
    "pyinstaller>=6.13.0",
    "pyqt6>=6.9.0",
    "pyside6>=6.9.0",
]
